import {Platform, StyleSheet} from 'react-native';
//import themes from 'themes';
const styles = StyleSheet.create({
  popupContainer: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  popup: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 10,
    width: 500,
    maxHeight: 550,
  },
  popupTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  fieldTitle: {
    fontWeight: 'bold',
    marginBottom: 11,
    width: 108,
    height: 19,
    //fontFamily: themes.fonts.fontRegular,
    fontSize: 12.7,
    letterSpacing: 0,
    textAlign: 'left',
    color: '#1c1939',
    marginTop: 15,
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 35,
    alignContent: 'center',
    // position: 'absolute',
    // bottom: 0,
    width: '100%',
    backgroundColor: 'white',
  },
  buttonPopup: {
    color: 'blue',
   // marginRight: themes.spacing(8),
   // paddingHorizontal: themes.spacing(8),
    width: 200,
    height: 55,
  },
  textInput: {
    width: '100%',
    borderRadius: 6,
    borderWidth: 1,
   // borderColor: themes.colors.primary,
   // color: themes.colors.primary,
    fontSize: 16,
   // fontFamily: themes.fonts.fontRegular,
  },
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    // marginBottom: 16,
  },
  childrenContainer: {
    backgroundColor: '#FFF',
    // padding: 20,
    borderRadius: 5,
    marginBottom: 23,
  },
  pickerItemStyle: {
    // height: 200,
    color: 'black',
    // paddingHorizontal: 20,
    backgroundColor: 'blue',
    // fontSize: 50,
    // paddingVertical: themes.spacing(8),
    // alignContent: 'center',
    // borderColor: themes.colors.grey[100],
    // borderWidth: 1,
    // shadowOffset: {width: 0, height: 2},
    // shadowOpacity: 0.9,
    // shadowRadius: 20,
    // elevation: 3,
  },
  pickerContainer: {
    borderRadius: 10,
    // borderColor: themes.colors.grey[100],
    borderWidth: 1,
  },
  pickerStyle: {
    height: 58,
    borderRadius: 10,
    padding: 5,
    ...Platform.select({
      web: {
        height: 58,
        borderRadius: 10,
        paddingHorizontal: 5,
      },
    }),
  },
  selectContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    // borderColor: themes.colors.primary,
    backgroundColor: 'transparent',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 7,
    // paddingHorizontal: themes.spacing(15),
    height: 50,
    ...Platform.select({
      web: {
        // height: themes.spacing(45),
      },
    }),
  },
  pickerContainerStyle: {
    borderRadius: 10,
    position: 'relative',
    // top: 50,
    width: '100%',
    // backgroundColor: themes.colors.white,
    zIndex: 10,
    // padding: themes.spacing(15),
    alignContent: 'center',
    // borderColor: themes.colors.grey[100],
    borderWidth: 1,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 20,
    elevation: 3,
    maxHeight: 400,
  },
  pickerContainerStyleAndroid: {
    borderRadius: 10,
    // position: 'absolute',
    // top: 50,
    width: '100%',
    // backgroundColor: themes.colors.white,
    zIndex: 10,
    // padding: themes.spacing(15),
    alignContent: 'center',
    // borderColor: themes.colors.grey[100],
    borderWidth: 1,
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.9,
    shadowRadius: 20,
    elevation: 3,
    maxHeight: 200,
    marginTop : 10,
  },
  pickerLabel: {
    paddingVertical: 5,
    position: 'relative',
    zIndex: 2,
    width : 100,
    // borderBottomColor: themes.colors.grey[300],
    borderBottomWidth: 1,
  },
  iconBorder: {
    // borderColor: themes.colors.primary,
    borderRadius: 10,
    padding: 5,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  uploadIcon: {
    alignSelf: 'flex-end',
    marginRight: 15,
    marginVertical: 10,
    height: 20,
  },
  modalContent: {zIndex: 99999},
  imageName: {marginTop: 4, marginLeft: 5},
  upload: {marginBottom: 5},
  input: {marginTop: 10, marginRight: 120},
  toastStyleBase: {
    // minHeight: themes.spacing(40),
    // maxWidth: themes.spacing(300),
    // minWidth: themes.spacing(300),
    borderRadius: 13,
    // backgroundColor: themes.colors.orange[200],
    justifyContent: 'flex-start',
    // paddingHorizontal: themes.spacing(16),
    // paddingTop: themes.spacing(10),
    // paddingBottom: themes.spacing(10),
    flexDirection: 'row',
  },
  closeIcon: {
    position: 'absolute',
    right: 10,
    top: 10,
    tintColor: '#fff',
  },
  toastText: {
    //color: themes.colors.white,
  },
});

export default styles;